### ISSUE TITLE
Composer installation of mastercrud errors:

### ISSUE THREAD

**Issue by rapgithub** [atk4/mastercrud#12]
None of the below installation are correct...something is missing... 

Installing mastercrud gives me the error:

[InvalidArgumentException]                                                   
  Could not find a matching version of package atk4masterCRUD. Check the pack  
  age spelling, your version constraint and that the package is available in   
  a stability which matches your minimum-stability (stable).             

Installing atk4crudception gives me the error:

  [InvalidArgumentException]                                                   
  Could not find a matching version of package atk4crudception. Check the pac  
  kage spelling, your version constraint and that the package is available in  
   a stability which matches your minimum-stability (stable).                  

any tips for installation without this errors!!

**Comment by rapgithub** [comment]
errors fixed!! the documentation is not written correctly installation must be with slash forward not backward!!!

like this composer require atk4/mastercrud

finally I got it working!!!
better to change the documentation texts and put the slash forward ...

thanks

**Comment by rapgithub** [comment]
but composer require atk4\crudception or composer require atk4/crudception does not work yet problem as above!! 

  [InvalidArgumentException]                                                   
  Could not find a matching version of package atk4crudception. Check the pac  
  kage spelling, your version constraint and that the package is available in  
   a stability which matches your minimum-stability (stable).

**Comment by romaninsh** [comment]
I have cleaned up readme and changed slash.
