### ISSUE TITLE
crudception cannot be installed!! 

### ISSUE THREAD

**Issue by rapgithub** [atk4/mastercrud#17]
composer require atk4\crudception 

does not work!!

I tried also

composer require atk4/crudception:dev-master

the same problem

Error:

  [InvalidArgumentException]                                                   
  Could not find a matching version of package atk4/crudception. Check the pa  
  ckage spelling, your version constraint and that the package is available i  
  n a stability which matches your minimum-stability (dev).

**Comment by romaninsh** [comment]
duplicate.
