### ISSUE TITLE
Refactor default view page

### ISSUE THREAD

**Issue by romaninsh** [atk4/mastercrud#21]
Currently when you click on the record you arrive at the page with several tabs. I'd like to clean up this screen and make it more usable.

1. No tabs - CRUDs should follow below the main screen.
2. no form - use read-only card instead
3. allow developer to specify a custom View (if he does not like card)
4. display "actions" on the side like "Edit" and "Delete"
5. potentially we would like to have "history" displayed on the side of a card: (https://github.com/atk4/audit/issues/23)
6. should be possible to display more buttons for additional actions

Screenshot for the reference:

![user-resource](https://user-images.githubusercontent.com/453929/50837519-ba47ed00-1353-11e9-8154-18b14ef3e6b7.png)

**Comment by roelleor** [comment]
It provides a better overview of the relations, nice! What would happen if you go one level deeper? I really like the current breadcrumb solution, does it stay? Symfony's sonata admin uses popups, but those kinda makes you feel lost sometimes.

An advantage of the current tab based view is when the details view contains a lot of fields one does not have to scroll all the way down. But when the read only fields are easily managed one could limit those of course.

**Comment by mvorisek** [comment]
closing in favor of https://github.com/atk4/ui/pull/2032
