### ISSUE TITLE
Ability to use Mastercrud inside tabs as it is with CRUD?

### ISSUE THREAD

**Issue by rapgithub** [atk4/mastercrud#25]
Is it possible to use mastercrud inside tabs as it is with CRUD only? 

I tried to do this but only works for one single model in this case Events model...

```php
  $tabs->addTab('Events', function($p) use($app) {

    $m = $p->add(new MasterCRUD());
    $m->setModel(new Events($app->db), ['Images'=>[]]);

  });
```

if I click the relational model Images the layout is destroyed and the url address change to this:

``html
?atk_narrow_tabs_tabssubview_virtualpage=cut&all_events_id=52
``

Instead the code below works inside tabs without issues, but only for one model definition...

```php
  $tabs->addTab('Events', function($p) use($app) {
    $m = $p->add('CRUD')->setModel(new Events($app->db));
  });
```

Any ideas how to make use of mastercrud inside tabs?
thanks for the ideas!

**Comment by mvorisek** [comment]
closing in favor of https://github.com/atk4/ui/issues/2070
