### ISSUE TITLE
Ability to set a different breadcrumb..

### ISSUE THREAD

**Issue by romaninsh** [atk4/mastercrud#3]
Suppose you are have client. Client `hasMany('Invoices', new Inovoice());`

Then when rendering breadcrumb, it should look like this:

`Client > Invoices > Invoice 248`

- Client = $client->getModelCaption()
- Invoices = name of the reference
- Invoice $client->ref('Invoices')->getModelCaption()
- 248 - $invoice->getTitle()

Note that getModelCaption would return localized data, but if we use reference, it needs localization. 

Additionally there should be a way to override the breadcrumb through injection.

**Comment by ibelar** [comment]
#4
